### ISSUE TITLE
Mention "Others Powered by MTGJSON" in the homepage TOC

### ISSUE THREAD

**Issue by allentiak** [mtgjson/mtgjson-website#396] opened 2020-02-21 04:12 UTC
### Steps to reproduce

Go to https://mtgjson.com/.
Scroll down to "Supporters". Continue scrolling down. You will find a section "Others Powered by MTGJSON".

### What is expected?

The section "Others Powered by MTGJSON" should also appear in the homepage TOC.

### What is actually happening?

It does not appear.

### Other relevant information
Maybe [supporters.json](https://github.com/mtgjson/mtgjson-website/blob/master/docs/.vuepress/public/resources/supporters.json) should be split into `supporters.json` and `powered-by.json`?

**Comment by ZeldaZach** [comment] 2020-02-21 04:17
Just took a look on three separate devices, but I see the appropriate contents... Can you try clearing your cache?

**Comment by allentiak** [comment] 2020-02-21 04:31
I did, but no luck (see screenshot below).

The problem seems to be in [the corresponding README.md](https://github.com/mtgjson/mtgjson-website/blob/master/docs/README.md).

![Screenshot from 2020-02-21 01-20-15](https://user-images.githubusercontent.com/1922297/75004366-9c4f2600-5449-11ea-89eb-5d46655fda44.png)

**Comment by allentiak** [comment] 2020-02-21 04:32
### Other relevant information
Maybe [supporters.json](https://github.com/mtgjson/mtgjson-website/blob/master/docs/.vuepress/public/resources/supporters.json) should be split into `supporters.json` and `powered-by.json`?

**Comment by ZeldaZach** [comment] 2020-02-21 04:37
Oh, you're referring to the sidebar! Yeah, the page is generated dynamically and it isn't included on the sidebar. Not a bug, but maybe a feature to consider.

**Comment by omfgitsmark** [comment] 2020-02-26 01:03
It is a subsection under **Supporters**, the sections being **Our Patreon Supporters** and **Others Powered by MTGJSON**. If one is on the sidebar it'd only make sense to put the other, but I really don't think it should be on the sidebar, the sidebar is cluttered enough :grin:

**Comment by allentiak** [comment] 2020-02-26 01:42
Are "Others powered by..." actual supporters? I think they are users... I mean, one project could be in either one or both lists...



I think the following reflects reality more accurately:
```
<h2>Supporters</h2>
    <h3>Our Patreon Supporters</h3>
<h2>Others Powered by MTGJSON</h2>
```

Maybe [supporters.json](https://github.com/mtgjson/mtgjson-website/blob/master/docs/.vuepress/public/resources/supporters.json) should be split into `supporters.json` and `powered-by.json` (or something like that)?

**Comment by allentiak** [comment] 2020-02-26 01:43
I meant:
```
<h2>Supporters</h2>
<h2>Projects Powered by MTGJSON</h2>
```

**Comment by allentiak** [comment] 2020-02-26 01:50
On Tue, 25 Feb 2020, 22:03 Mark Cheese, <notifications@github.com> wrote:

> I really don't think it should be on the sidebar, the sidebar is cluttered
> enough 😁
>

Hadn't I scrolled down at "Supporters", I would have never found the "Made
with" section...

>
>

**Comment by staghouse** [comment] 2020-03-29 03:05
TOC is going away for this page with v5. Closing.

**Closed by staghouse** 2020-03-29 03:05 UTC
Labels: bug
